name: advanced_pagination
description: "Controller-first pagination for Flutter with page/offset/cursor support, list/grid/sliver widgets, cache + prefetch, and customizable states."
version: 0.1.0
homepage: https://github.com/patoliavishal/flutter_advanced_paginatio
repository: https://github.com/patoliavishal/flutter_advanced_paginatio
issue_tracker: https://github.com/patoliavishal/flutter_advanced_paginatio/issues
topics:
  - pagination
  - infinite-scroll
  - flutter
  - listview
  - gridview

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
